using Ivory.Type;
int[] array = new int[0];

int i;
int res;
for (i = 0; i < 10000; i++)
{
	array.add(i);
}
for (i = 0; i < array.size(); i++) {
	res += array[i];
}
println(a + glue);
println(glue);
println(glue + b);
println(b + (string)Animals.Monkey);

enum Animals {
	Monkey,
	Donkey,
	Tiger
}

const string a = "abc";
const string glue = (string)(double)((int)123.9);
const int b = 1223;

delegate int MoreArgs(...);
delegate int path(...);
int carg(...a)
{
	println((string)a[0]);
}

MoreArgs f = carg;
object o1 = f;
object o2 = carg;
f("hi, it's me");
((path)o1)("hi, it's me");

object o3 = 123;
Type t = typeof("123");
println(t.tostring());
