#include <stdio.h>
#include "../Ivoryc.h"


char *st_Ivory_lang_ivh_text[] = {
    "//Ivory.lang\n",
    "void print(string str);\n",
    "void println(string str) {\n",
    "    print(str + \"\\n\");\n",
    "}\n",
    "\n",
    "public class File {\n",
    "    native fp;\n",
    "    constructor initialize(native fp) {\n",
    "\t    this.fp = fp;\n",
    "    }\n",
    "}\n",
    "\n",
    "File fopen(string file_name, string mode);\n",
    "string fgets(File file);\n",
    "void fputs(string str, File file);\n",
    "void fclose(File file);\n",
    "\n",
    "double to_double(int int_value) {\n",
    "    return int_value;\n",
    "}\n",
    "\n",
    "int to_int(double double_value) {\n",
    "    return double_value;\n",
    "}\n",
    "\n",
    "int parse_int(string str);// throws NumberFormatException;\n",
    "double parse_double(string str);// throws NumberFormatException;\n",
    "long double parse_long_double(string str) ;\n",
    "\n",
    "void randomize();\n",
    "int random(int range);\n",
    "\n",
    "class StackTrace {\n",
    "    int\tline_number;\n",
    "    string file_name;\n",
    "    string function_name;\n",
    "}\n",
    "\n",
    "abstract public class Exception {\n",
    "    public string message;\n",
    "    public StackTrace[] stack_trace;\n",
    "    public void print_stack_trace() {\n",
    "\tint i;\n",
    "\tprintln(\"Exception occured. \" + this.message);\n",
    "\tfor (i = 0; i < this.stack_trace.size(); i++) {\n",
    "\t    println(\"\\tat \" \n",
    "\t\t    + this.stack_trace[i].function_name\n",
    "\t\t    + \"(\" + this.stack_trace[i].file_name\n",
    "\t\t    + \":\" + this.stack_trace[i].line_number + \")\");\n",
    "\t}\n",
    "    }\n",
    "    public virtual constructor initialize() {\n",
    "\tthis.stack_trace = new StackTrace[0];\n",
    "    }\n",
    "}\n",
    "\n",
    "abstract public class BugException : Exception {\n",
    "}\n",
    "\n",
    "abstract public class RuntimeException : Exception {\n",
    "}\n",
    "\n",
    "public class NullPointerException : BugException {\n",
    "}\n",
    "\n",
    "public class ArrayIndexOutOfBoundsException : BugException {\n",
    "}\n",
    "\n",
    "public class StringIndexOutOfBoundsException : BugException {\n",
    "}\n",
    "\n",
    "public class DivisionByZeroException : RuntimeException {\n",
    "}\n",
    "\n",
    "public class MultibyteCharacterConvertionException : RuntimeException {\n",
    "}\n",
    "\n",
    "public class ClassCastException : BugException {\n",
    "}\n",
    "\n",
    "public abstract class ApplicationException : Exception {\n",
    "}\n",
    "\n",
    "public class NumberFormatException : ApplicationException {\n",
    "}\n",
    "\n",
    "public class OutOfIteratorException : ApplicationException {\n",
    "}\n",
    "\n",
    "public class NewIteratorException : ApplicationException {\n",
    "}\n",
    "\n",
    "delegate int HogeDelegate(int value);\n",
    "\n",
    "// BUGBUG for test routine\n",
    "string test_native(object o);\n",
    "\n",
    "void foo_file(File file) {\n",
    "}\n",
    "\n",
    "//object\n",
    "/*public class test_class {\n",
    "    public string str;\n",
    "    public constructor initialize(string str) { this.str = str; }\n",
    "    //object get_object_from_string(string value);\n",
    "}*/\n",
    "\n",
    NULL
};
char *st_Ivory_lang_ivy_text[] = {
    "using Ivory.lang;\n",
    "\n",
    "native __fopen(string file_name, string mode);\n",
    "string __fgets(native fp);\n",
    "void __fputs(string str, native fp);\n",
    "void __fclose(native fp);\n",
    "\n",
    "File fopen(string file_name, string mode) {\n",
    "    native fp = __fopen(file_name, mode);\n",
    "    if (fp == null) {\n",
    "\treturn null;\n",
    "    } else {\n",
    "\treturn new File(fp);\n",
    "    }\n",
    "}\n",
    "\n",
    "string fgets(File file) {\n",
    "    return __fgets(file.fp);\n",
    "}\n",
    "\n",
    "void fputs(string str, File file) {\n",
    "    __fputs(str, file.fp);\n",
    "}\n",
    "\n",
    "void fclose(File file) {\n",
    "    __fclose(file.fp);\n",
    "}\n",
    NULL
};
char *st_Ivory_Math_ivh_text[] = {
    "double fabs(double z);\n",
    "double pow(double z, double x);\n",
    "double fmod(double number, double divisor);\n",
    "double ceil(double z);\n",
    "double floor(double z);\n",
    "double sqrt(double z);\n",
    "double exp(double z);\n",
    "double log10(double z);\n",
    "double log(double z);\n",
    "double sin(double radian);\n",
    "double cos(double radian);\n",
    "double tan(double radian);\n",
    "double asin(double arg);\n",
    "double acos(double arg);\n",
    "double atan(double arg);\n",
    "double atan2(double num, double den);\n",
    "double sinh(double value);\n",
    "double cosh(double value);\n",
    "double tanh(double value);\n",
    NULL
};
char *st_Ivory_IO_ivh_text[] = {
    "/* Ivory.IO package \n",
    " * provide some function for I/O stream controlling\n",
    " */\n",
    "string gets();\n",
    "int puts(string str);\n",
    "int putc(int ch);\n",
    NULL
};
char *st_Ivory_System_ivh_text[] = {
    "/* Ivory.System package \n",
    " * ported from stdlib.h\n",
    " */\n",
    "void abort();\n",
    "void exit(int status);\n",
    "int system(string s);\n",
    "string getenv(string name);\n",
    NULL
};
char *st_Ivory_Type_ivh_text[] = {
    "/* Ivory.Type package\n",
    " */\n",
    "enum TypeID {\n",
    "\tVOID_TYPE,\n",
    "    BOOLEAN_TYPE,\n",
    "    INT_TYPE,\n",
    "    DOUBLE_TYPE,\n",
    "    LONG_DOUBLE_TYPE,\n",
    "    OBJECT_TYPE,\n",
    "    STRING_TYPE,\n",
    "    CLASS_TYPE,\n",
    "    DELEGATE_TYPE,\n",
    "    ENUM_TYPE,\n",
    "    NULL_TYPE,\n",
    "    NATIVE_POINTER_TYPE,\n",
    "    BASE_TYPE,\n",
    "    ITERATOR_TYPE,\n",
    "\tUNCLEAR_TYPE,\n",
    "    UNSPECIFIED_IDENTIFIER_TYPE\n",
    "}\n",
    "\n",
    "public class Type {\n",
    "\tprivate int code;\n",
    "\tpublic TypeID type_id;\n",
    "\n",
    "\tconstructor initialize(int code) {\n",
    "\t    this.code = code;\n",
    "\t\tswitch (code) {\n",
    "\t\t\tcase void:\t\t\t\tthis.type_id = TypeID.VOID_TYPE;\n",
    "\t\t\tcase bool:\t\t\t\tthis.type_id = TypeID.BOOLEAN_TYPE;\n",
    "\t\t\tcase int:\t\t\t\tthis.type_id = TypeID.INT_TYPE;\n",
    "\t\t\tcase double:\t\t\tthis.type_id = TypeID.DOUBLE_TYPE;\n",
    "\t\t\tcase long double:\t\tthis.type_id = TypeID.LONG_DOUBLE_TYPE;\n",
    "\t\t\tcase object:\t\t\tthis.type_id = TypeID.OBJECT_TYPE;\n",
    "\t\t\tcase string:\t\t\tthis.type_id = TypeID.STRING_TYPE;\n",
    "\t\t\tcase 8:\t\t\t\t\tthis.type_id = TypeID.CLASS_TYPE;\n",
    "\t\t\tcase 9:\t\t\t\t\tthis.type_id = TypeID.DELEGATE_TYPE;\n",
    "\t\t\tcase 10: \t\t\t\tthis.type_id = TypeID.ENUM_TYPE;\n",
    "\t\t\tcase 11:\t\t\t\tthis.type_id = TypeID.NULL_TYPE;\n",
    "\t\t\tcase native:\t\t\tthis.type_id = TypeID.NATIVE_POINTER_TYPE;\n",
    "\t\t\tcase 13:\t\t\t\tthis.type_id = TypeID.BASE_TYPE;\n",
    "\t\t\tcase ArrayIterator:\t\tthis.type_id = TypeID.ITERATOR_TYPE;\n",
    "\t\t\tcase 15:\t\t\t\tthis.type_id = TypeID.UNCLEAR_TYPE;\n",
    "\t\t\tcase 16:\t\t\t\tthis.type_id = TypeID.UNSPECIFIED_IDENTIFIER_TYPE;\n",
    "\t\t}\n",
    "    }\n",
    "\n",
    "\tpublic string tostring() {\n",
    "\t\treturn (string)this.type_id;\n",
    "\t}\n",
    "}\n",
    "\n",
    "int __typeof(object o);\n",
    "Type typeof(object o) {\n",
    "\tint code = __typeof(o);\n",
    "\tType ret = new Type(code);\n",
    "\treturn ret;\n",
    "}\n",
    NULL
};
char *st_Ivory_Time_ivh_text[] = {
    "/* Ivory.Time package\n",
    " */\n",
    "void usleep(int micro_seconds);\n",
    "void sleep(int millisecond);\n",
    NULL
};
char *st_Ivory_Iterator_ivh_text[] = {
    "/* Ivory.Iterator package\n",
    " */\n",
    "public interface Iterator {\n",
    "\tpublic object next() throws OutOfIteratorException;\n",
    "\tpublic bool hasNext();\n",
    "\tpublic object current() throws NewIteratorException;\n",
    "}\n",
    "\n",
    "/* Iterators */\n",
    "\n",
    "/*\n",
    " * { ListIterator }\n",
    " * can be initialized by { ArrayIterator }\n",
    " * inherit interface { Iterator }\n",
    " */\n",
    "const OUT_OF_ITERATOR_ERR = \"out of iterator\";\n",
    "const NEW_ITERATOR_ERR = \"used new iterator without initializing\";\n",
    "\n",
    "public class ListIterator : Iterator\n",
    "{\n",
    "\tpublic int size;\n",
    "\tpublic int cursor;\n",
    "\tpublic object[] data;\n",
    "\n",
    "\tpublic override object next() {\n",
    "\t\tOutOfIteratorException e = new OutOfIteratorException();\n",
    "\t\te.message = OUT_OF_ITERATOR_ERR;\n",
    "\n",
    "\t\tif (this.cursor+1 < this.size) {\n",
    "\t\t\tthis.cursor += 1;\n",
    "\t\t\treturn this.data[this.cursor];\n",
    "\t\t} else {\n",
    "\t\t\tthrow e;\n",
    "\t\t}\n",
    "\t\treturn null;\n",
    "\t}\n",
    "\tpublic override object current() {\n",
    "\t\tNewIteratorException e = new NewIteratorException();\n",
    "\t\te.message = NEW_ITERATOR_ERR;\n",
    "\n",
    "\t\tif (this.cursor < 0) {\n",
    "\t\t\tthrow e;\n",
    "\t\t\treturn null;\n",
    "\t\t}\n",
    "\t\treturn this.data[this.cursor];\n",
    "\t}\n",
    "\tpublic override bool hasNext() {\n",
    "\t\tif (this.cursor+1 < this.size) {\n",
    "\t\t\treturn true;\n",
    "\t\t}\n",
    "\t\treturn false;\n",
    "\t}\n",
    "\tpublic constructor initialize(ArrayIterator ite) {\n",
    "\t\tthis.data = new object[0];\n",
    "\t\tfor (this.size = 0; ite.hasNext(); this.size++) {\n",
    "\t\t\tthis.data.add((object)ite.next());\n",
    "\t\t}\n",
    "\n",
    "\t\tthis.cursor = -1;\n",
    "\t}\n",
    "}\n",
    NULL
};
char *st_Ivory_Container_Stack_ivh_text[] = {
    "public interface IStack <TYPE>\n",
    "{\n",
    "\tpublic TYPE pop();\n",
    "\tpublic int push(TYPE target);\n",
    "}\n",
    "\n",
    "public class Stack <T> : IStack with<T>, IStack with<T>\n",
    "{\n",
    "\tpublic int __LAST;/* point to the last element */\n",
    "\tpublic T[] __DATA;\n",
    "\t/*public constructor initialize(...data)\n",
    "\t{\n",
    "\t\tthis.__DATA = new T[0];\n",
    "\n",
    "\t\tfor (this.__LAST = 0; this.__LAST < data.size(); this.__LAST++) {\n",
    "\t\t\tthis.__DATA.add((T)(data[this.__LAST]));\n",
    "\t\t}\n",
    "\t\tthis.__LAST--;\n",
    "\t}*/\n",
    "\tpublic constructor initialize()\n",
    "\t{\n",
    "\t\tthis.__DATA = new T[0];\n",
    "\t\tthis.__LAST = -1;\n",
    "\t}\n",
    "\tpublic override T pop()\n",
    "\t{\n",
    "\t\tT pop = this.__DATA[this.__LAST];\n",
    "\t\tthis.__DATA.remove(this.__LAST);\n",
    "\t\tthis.__LAST--;\n",
    "\t\treturn pop;\n",
    "\t}\n",
    "\tpublic override int push(T target)\n",
    "\t{\n",
    "\t\tthis.__DATA.add(target);\n",
    "\t\tthis.__LAST++;\n",
    "\t\treturn this.__LAST;\n",
    "\t}\n",
    "}\n",
    NULL
};

BuiltinScript Ivyc_builtin_script[] = {
    {"Ivory.lang", IVH_SOURCE, st_Ivory_lang_ivh_text},
    {"Ivory.lang", IVY_SOURCE, st_Ivory_lang_ivy_text},
    {"Ivory.Math", IVH_SOURCE, st_Ivory_Math_ivh_text},
    {"Ivory.IO", IVH_SOURCE, st_Ivory_IO_ivh_text},
    {"Ivory.System", IVH_SOURCE, st_Ivory_System_ivh_text},
    {"Ivory.Type", IVH_SOURCE, st_Ivory_Type_ivh_text},
    {"Ivory.Time", IVH_SOURCE, st_Ivory_Time_ivh_text},
    {"Ivory.Iterator", IVH_SOURCE, st_Ivory_Iterator_ivh_text},
    {"Ivory.Container.Stack", IVH_SOURCE, st_Ivory_Container_Stack_ivh_text},
    {NULL, IVY_SOURCE, NULL}
};
